actor_type: generic
actor_templates:
  default:
    attributes:
    - attribute: state
      values:
        "on":
          service: homeassistant.turn_on
        "off":
          service: homeassistant.turn_off
